# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcf51dc45e232a257a22ffdf694db55775dc04564709e9ad22c0df4873519f4566340cde61884ef2568918d10ad1edc8be3fafa59e7d59072ea2b142ee05c12a

test:
  secret_key_base: d298cfa83ec388c52ac2b29ac58d1187b0e2ecc86d67f6d88e2c535bdff60eeb4f6adc04cfa1dd1a0b44755fcba20f0ea1824595d9389865fea531f27b9e30e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
